### ISSUE TITLE
.install is not working 🥲, when I enter to install plugin it shows the instagram link to download 🥲

### ISSUE THREAD

**Issue by LUTTAPICK** [souravkl11/Raganork-legacy#39]
.install is not working 🥲, when I enter to install plugin it shows the instagram link to download 🥲

**Comment by souravkl11** [comment]
> .install is not working 🥲, when I enter to install plugin it shows the instagram link to download 🥲

It means that your plugin format may have errors. The command should be like ```"help ?(.*)"```. And the support for this project will end soon. Continue using my md bot. Link in readme!
